### ISSUE TITLE
not showing most recent polygons

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#11]
the most recent polygons are already present in the postgis database, but still not being shown in visualization. Why it that the case? It the query not working properly?

See for example `id_cogerh=4055`
![not_showing_current_polys](https://user-images.githubusercontent.com/4688726/39196025-6d3a2cd2-47e1-11e8-8b78-87e1a2c4a03b.png)

**Comment by schuem** [comment]
Apparently there is an error in the geometry, i guess it is not valid...i could implement a trigger to fix the geometry on inserts and also throw an error message if this happens in the visualization

**Comment by jmigueldelgado** [comment]
what could be an error in the geometry? a hole could be an error? Maybe I can do something to fix this upstream of the INSERT

**Comment by jmigueldelgado** [comment]
by the way the app is looking nice !

**Comment by schuem** [comment]
There are some self intersections

**Comment by schuem** [comment]
Thanks, i've seen in your screenshot that the 3 divs don't have the exact sizes, in my screen they are looking good. I will make them responsive to the screen size

**Comment by jmigueldelgado** [comment]
I am trying this upstream of ogr2ogr: https://www.r-spatial.org/r/2017/03/19/invalid.html

**Comment by schuem** [comment]
with this projection? http://spatialreference.org/ref/epsg/wgs-84-utm-zone-32s/

**Comment by jmigueldelgado** [comment]
zone 32? why? do you mean 23? I am using epsg:4326 (lat long).

**Comment by jmigueldelgado** [comment]
st_make_valid from R's sf seems to work for the first testing so I will introduce it before ogr2ogr.

**Comment by schuem** [comment]
of course 23 ... so the original data is in this projection(EPSG:32723) i guess.
Just to be sure so i can reproject the data on the db insert

**Comment by jmigueldelgado** [comment]
the polygons being inserted are already in latlong! no need to reproject.

**Comment by schuem** [comment]
i'm refering to the cogerh static dataset

**Comment by jmigueldelgado** [comment]
oh, yes, that is EPSG:32723. It is defined as latlong but it is utm. Let me transform and save it again correctly in the repo

**Comment by jmigueldelgado** [comment]
ok, the projection is now correctly defined as `EPSG:32723` in the dataset,  so now you have to project it to your purpose. The dataset is now called `funceme.geojson`. It is in fact a funceme product and not cogerh, so I thought we might start calling it correctly...

**Comment by schuem** [comment]
Ok, this really caused me a headache. The map query didn't return any results even though i was sure the postgis query is right. The projection was still wrong, it is EPSG: 32724.

**Comment by jmigueldelgado** [comment]
Man, you are right. UTM 23 is the one for Sao Francisco river. I should
have known. This one is on me, really sorry!

A qui, 26/04/2018, 16:14, schuem <notifications@github.com> escreveu:

**Comment by jmigueldelgado** [comment]
ok, issue still open but slightly but slightly different: the watermask shown is apparently the correct one, but after clicking a polygon the table and graph displayed are wrong and stuck in February, although the most recent watermasks are from May. Please try to fix this before going on with the hav extraction. I am home today, tomorrow, thursday and friday I will be in the office.

**Comment by schuem** [comment]
fixed
