### ISSUE TITLE
units of area to hectar

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#13]
please change the area units in the graph and tables to hectar (1 ha = 10 000 sqm).

**Comment by jmigueldelgado** [comment]
Hi Martin,
sorry about this, but I need you change the units again. I finally decided to employ Molle's expression for estimating volume from surface area.

**I need you to replace hectare with the following expression, which will yield an estimated volume in hm^3:**

`V=0.001*(A/2700)^(1.5882)`

`A` is area in square meters;
`V` is volume in hm^3 (million cubic meters, a usual unit for reservoir volume)

**Comment by schuem** [comment]
changed to display estimated volume in chart
