### ISSUE TITLE
sending jquery GET request to node.js server not working outside the uni network

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#16]
In `index.html` the following client request is not reaching the server:
`$.get('http://141.89.96.184:5155',{'id_funceme':idtest});`

The server was up in the console by `node mongolisten.js`

**Comment by jmigueldelgado** [comment]
Same behaviour in the zim server.

... and yes, I already allowed the port on the firewall ...

**Comment by schuem** [comment]
Ok, why are you using a node.js server now? If you want to migrate to the zim server, please let me know it so i could help you.

**Comment by jmigueldelgado** [comment]
yes, I am migrating to zim server, but some requests are not working, still debugging... the node.js works for processing server side requests of local files and easier processing of mongodb requests. But maybe it will not be necessary, still checking.

**Comment by jmigueldelgado** [comment]
and I think this issue is solve, I will check this tomorrow and close it if that is the case

**Comment by jmigueldelgado** [comment]
Two issues here:

- outside the university network the ajax GET request won't reach the nodejs server
- inside the university network, the request is sent and arrives, but 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://seca-vista.geo.uni-potsdam.de:3000/?idRequest=12555. (Reason: CORS request did not succeed).
