### ISSUE TITLE
Security Error when loading libraries from API in zim server

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#17]
Following error occurs when loading libraries in `index.html`

The address is `http://seca-vista.geo.uni-potsdam.de/watermask/`

> 
> >SecurityError: The operation is insecure. ol.js:198 
> > aj.prototype.s
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:198:279
> > kj.prototype.Ti
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:206:348
> > k.tg
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:126:129
> > <anonymous>
> > http://seca-vista.geo.uni-potsdam.de/watermask/:412:12
> > b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:46:348
> > Sc.prototype.b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:49:206
> > k.bi
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:129:352
> > b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:46:348
> > Sc.prototype.b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:49:206
> > k.mq
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:73:388
> > b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:46:348
> > Sc.prototype.b
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:49:206
> > Od
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:70:302
> > k.Lp
> > https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol.js:59:399
> > <anonymous> self-hosted:984:17

**Comment by schuem** [comment]
Maybe try to add the parameter 'crossOrigin': 'anonymous' to the layer sources, see [here](https://gis.stackexchange.com/questions/269937/openlayers-4-method-foreachlayeratpixel-throws-securityerror-the-operation-is)
