### ISSUE TITLE
Error on clicking features

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#19]
After clicking features the following error occurs:

> XML Parsing Error: no root element found
> Location: http://seca-vista.geo.uni-potsdam.de/watermask/test.php?id=20476
> Line Number 7, Column 1: test.php:7:1

**Comment by schuem** [comment]
Mhh, there are only 6 lines of code in test.php. It looks like select.php is not included at all. Directly requesting select.php with a valid ID does not fix it but returns the last few lines of the code. I guess PHP is not directly supported by node.js so you need javascript to parse and execute php files, see [here](https://medium.com/@MartinMouritzen/how-to-run-php-in-node-js-and-why-you-probably-shouldnt-do-that-fb12abe955b0)

**Comment by jmigueldelgado** [comment]
but I am not even running node in this application! I disabled all the node related stuff. This is something different. I will have a look at it tomorrow again. thanks!

**Comment by schuem** [comment]
Ok, i installed and activated php for apache. Now you get a more helpful error:
Warning: parse_ini_file ... failed to open stream: No such file or directory in ...

**Comment by jmigueldelgado** [comment]
ok, we are now moving on with shiny and it is working, so until you come back to this project we will avoid javascript :)
