### ISSUE TITLE
some features are not displayed in d3

### ISSUE THREAD

**Issue by schuem** [schuem/watermask2map#3]

**Comment by schuem** [comment]
there seems to be a relation between pg_fetch_all($result) and the returned variable
in the case when the result only contains one row (i.e. one entry in the db). Then the returned value is NOT an array and cannot be used in the foreach loop

**Comment by schuem** [comment]
There are a lot of empty geometries in the table. The entries are fetched, but in the further processing all subsequent rows will be lost. Besides, d3 doesn't plot any geometries at all if there is one empty feature.

**Comment by jmigueldelgado** [comment]
Ok, I will address this upstream of the postgis, by filtering out empty
features. This issue probably only affects multipolygons, right?

A sex, 27/04/2018, 12:47, schuem <notifications@github.com> escreveu:

**Comment by jmigueldelgado** [comment]
when reading geojson files with json in python a bracket in the multipolygon coordinates gets lost on the way. After this point, invalid geojson are inserted in mongodb, queried and read as empty polygons. I am fixing this now.

**Comment by jmigueldelgado** [comment]
> when reading geojson files with json in python a bracket in the multipolygon coordinates gets lost on the way
This was fixed, still many multipolygons are not displayed. One reason is that this error already occurred in the past and once one multipolygon has an error it affects all the multipols in display. Maybe it is time to change the display from the many previous multipols to only the most recent. I will open an issue for this
