### ISSUE TITLE
add funceme dataset as static layer

### ISSUE THREAD

**Issue by jmigueldelgado** [schuem/watermask2map#7]
the funceme dataset would be very helpful for visual validation of the results at this stage.

**Comment by schuem** [comment]
could you once again tell me the name of the dataset?

**Comment by jmigueldelgado** [comment]
I uploaded it [here](https://github.com/jmigueldelgado/buhayra/tree/master/buhayra/auxdata) by mistake, so you can download it if you want. Otherwise it is on the webserver under buhayra/buhayra/auxdata/cogerh.geojson

**Comment by schuem** [comment]
Would be really nice to adjust the offset if possible, but there really is no consistent pattern.

**Comment by jmigueldelgado** [comment]
Agree, but for now the dataset is only for visual validation purposes. With time I hope to get a new and better static dataset. Let's leave this one as is and focus on obtaining a new one from our own database in the future.
